# Generated by Django 3.2.11 on 2022-09-06 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bloggingapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createblog',
            name='like',
        ),
        migrations.AddField(
            model_name='createblog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createblog',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='createblog',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='createblog',
            name='image',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloggingapp.createblog')),
            ],
        ),
    ]
